# Generated by Django 2.0.2 on 2018-02-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180217_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Menge'),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Preis'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2018'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hersteller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titel'),
        ),
    ]
