# Generated by Django 2.0.2 on 2018-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180224_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Beschreibung'),
        ),
    ]
